apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  selector:
    matchLabels:
      app: dev
  replicas: 3
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: rokonzaman/django:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: master-pod-port
---
apiVersion: v1
kind: Service
metadata:
  name: dev-svc
  labels:
    app: dev
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: master-pod-port
    nodePort: 31113
    protocol: TCP
  selector:
    app: dev
