apiVersion: apps/v1
kind: Deployment
metadata:
  name: master_django
spec:
  selector:
    matchLabels:
      app: master_django
  replicas: 3
  template:
    metadata:
      labels:
        app: master_django
    spec:
      containers:
      - name: master_django
        image: rokonzaman/master_django:latest
        ports:
        - containerPort: 8000
          name: master-django-pod-port
---
apiVersion: v1
kind: Service
metadata:
  name: master_django
  labels:
    app: master_django
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: master-django-pod-port
    nodePort: 31112
    protocol: TCP
  selector:
    app: master_django
