apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
spec:
  selector:
    matchLabels:
      app: prod
  replicas: 3
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: prod
        image: rokonzaman/django:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: prod-port
---
apiVersion: v1
kind: Service
metadata:
  name: prod-svc
  labels:
    app: dev
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: prod-port
    nodePort: 31114
    protocol: TCP
  selector:
    app: prod
